server:
  port: 8080

spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
  datasource:
    druid:
      driver-class-name: ${exam.datasource.driver-class-name}
      url: jdbc:mysql://${exam.datasource.host}:${exam.datasource.port}/${exam.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: ${exam.datasource.username}
      password: ${exam.datasource.password}


mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）

logging:
  level:
    com:
      exam:
        mapper: debug
        service: info
        controller: info
redis:
  host: ${exam.redis.host}
  port: ${exam.redis.port}
  password: ${exam.redis.password}
  database: ${exam.redis.database}
exam:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: cloudFank
    # 设置jwt过期时间
    admin-ttl: 7200000
    # 设置前端传递过来的令牌名称
    admin-token-name: token
  alioss:
    endpoint: ${exam.alioss.endpoint}
    access-key-id: ${exam.alioss.access-key-id}Z
    access-key-secret: ${exam.alioss.access-key-secret}
    bucket-name: ${exam.alioss.bucket-name}
